name: CI32
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        julia-version:
          - "1.6"
          - "1"
          - "nightly"
        include:
          - os: windows-latest
            julia-version: "1"
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v1
        with:
          show-versioninfo: true
          arch: x86
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: heptazhou/julia-codecov@v1
